---
- name: Install all security, critical, and rollup updates without a scheduled task
  hosts: Test Group
  tasks:
    ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
