---
- name: Windows Update
  hosts: Test Group

  tasks:
  - name: Install all security, critical, and rollup updates without a scheduled task
    ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
