---
- name: Windows Update - Directory Servers
  hosts: directoryservers

  tasks:
    - name: Complete Windows Updates on Directory Servers
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
        reboot_timeout: 600

- name: Windows Update - Application Servers
  hosts: appservers

  tasks:
    - name: Complete Windows Updates on Application Servers
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
        reboot_timeout: 600

- name: Windows Update - Terminal Servers
  hosts: terminalservers

  tasks:
    - name: Complete Windows Updates on Terminal Servers
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
        reboot_timeout: 600

- name: Windows Update - General Servers
  hosts: generalservers

  tasks:
    - name: Complete Windows Updates on General Servers
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
        reboot_timeout: 600
